# Generated by Django 3.2 on 2021-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('dob', models.DateField(verbose_name='')),
                ('gender', models.CharField(max_length=50, verbose_name='')),
                ('locality', models.CharField(max_length=50, verbose_name='')),
                ('pin', models.PositiveIntegerField(verbose_name='')),
                ('state', models.CharField(choices=[('Aasam', 'Aasam'), ('bihar', 'bihar'), ('up', 'up')], max_length=50)),
                ('mobile', models.PositiveIntegerField(verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('job_city', models.CharField(max_length=50, verbose_name='')),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg', verbose_name='')),
                ('my_file', models.FileField(upload_to='doc', verbose_name='')),
            ],
        ),
    ]
