# Generated by Django 3.2 on 2021-08-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210813_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
    ]
